Repository vishanurag/Canvas-Editor, pull requests merged in 2024-10, with the labels that each got.

#9 feat: added the capitalise , small , bold and italic buttons to edit the text
  index.html
  src/Scripts/Canvas.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#14 feat: Enhance button responsiveness and input field styles for better mobil…
  index.html
  src/Styles/Responsive.css
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#20 Update README.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#21 feat: adding the background image and background color
  index.html
  src/Scripts/Canvas.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#28 fixed text disappearing issue
  index.html
  src/Scripts/Canvas.js
Labels: gssoc-ext, level1, hacktoberfest-accepted

#31 Add support for multiple text elements on canvas #26 UPDATE
  index.html
  src/Scripts/Canvas.js
Labels: gssoc-ext, level3, hacktoberfest-accepted

#49 Added shape palette
  index.html
  src/.vscode/settings.json
  src/Scripts/Canvas.js
  src/Styles/Style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#55 Corrected the overflow
  src/Styles/Style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#56 added gsap libraries to animate the website
  index.html
  src/Scripts/Canvas.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#39 Responsive Design: Improved Button and Text Box Sizes with Custom Hover Effects
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level3, hacktoberfest-accepted

#51 Background Color gradient
  src/Scripts/Canvas.js
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#68 Done Changes With Homepage Designing
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#71 Error Handling for File Upload
  src/Scripts/Canvas.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#65 added a new section of draw text using cursor
  edition.html
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#78 CONTRIBUTING.md
  Contributing.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#83 optimise canvas rendering
  src/Scripts/Canvas.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#75 Enhancing web page
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#63 Updated Readme.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#96 added contact us section the home page
  index.html
  src/Scripts/Canvas.js
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#105 added brightness, saturation, blur section also fix the two typo!!#74
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#103 Issue resolved - palette colour
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#110 Create about.html Closes # 82
  about.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#107 Font Size Mismatch in Canvas Text Update
  src/Scripts/Canvas.js
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#130 Added a Custom effect in Cursor
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#135 [FIX] Draw section added
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#136 BRUSH CLEAR CANVAS AND ERASER ADDED ISSUE NO. #104
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#90 Fix: Alignment and Spacing for Canvas and Control Panel
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#142 removed the horizontal scroll
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#159 Resolved issue: Contributing.md file redirect from README.md file
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#157 feat(font-button): Created a font button for bold, italics, uppercase…
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#169 Solved issue #138
  about.html
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#151 contact_us section visually appealing
  index.html
  src/Styles/Style.css
  src/Styles/contact_us_style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#154 Drag-and-Drop Feature #37
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#160 Update: Contributing.md
  Contributing.md
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#171 Issue #148 : fixed unvisible texts in canvas editor
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#172 now buttons are not shaking
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#176 Features: Sign Up and Login Page #112
  about.html
  index.html
  login.html
  signup.html
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#187 Fixed the bug #156
  index.html
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#184 About us page revamp
  about-us.html
  index.html
  resources/painting_image.jpg
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#173 changed the footer section in neat way
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#206 [BUGFIX] Fixed broken links and image path
  about-us.html
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#190 Welcome page and added some functionalities.
  index.html
  welcome.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#209 Feature: Implement GitHub Workflow for Automated Greetings
  .github/workflows/greetings.yml
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#217 Updated Social links #201
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#216 Add Issues & PR templates
  .github/Issue_templates/BUG_report_issue_template.md
  .github/Issue_templates/Feature_request_issue_template.md
  .github/Pull_Request_template.md
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#225 #120 fixed Mini chatbot
  .env.example
  boy.png
  chatbot.gif
  chatbot.html
  index.html
  src/Styles/Responsive.css
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#227 Added email validation
  login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#229 To adding animation effect to social media icons
  about-us.html
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#244 Dark Font Palette Issue #222
  about-us.html
  boy.png
  chatbot.gif
  chatbot.html
  index.html
  login.html
  src/Styles/Style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#235 changes made on footer part
  about-us.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#224 Added hyperlink to Anurag's Github profile
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#238 Added Review and Blog Page
  blog.html
  feature.png
  index.html
  review.html
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#252 Added a FAQ section
  Faq.html
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#327 Styled the Vertical Scrollbar.
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#321 docs: Add social Badges & fixed some padding & align on header
  README.md
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#276 feat: Improve Scroll Bar and Preloader
  about.html
  index.html
  login.html
  signup.html
  src/Scripts/preloader.js
  src/Styles/Style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#300 Updated SignUp and Login Page
  login.html
  signup.html
  src/Styles/signup.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#303 Added back to top button
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#350 Add Contributor Page to Display Project Contributors
  about-us.html
  contributors.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#291 Blog Page Added
  .vscode/settings.json
  Blog_page.html
  index.html
  src/Styles/Style_Blog_page.css
  src/images/about-bg.jpg
  src/images/art-design-1.jpg
  src/images/art-design-2.jpg
  src/images/art-design-3.jpg
  src/images/art-design-4.jpg
  src/images/art-design-5.jpg
  src/images/art-design-6.jpg
  src/images/banner-bg.jpg
  src/images/blog-p-1.jpg
  src/images/blog-p-2.jpg
  src/images/blog-p-3.jpg
  src/images/blog-p-4.jpg
  src/images/blog-p-5.jpg
  src/images/blog-p-6.jpg
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#338 adding underline hover
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#366 feat: Added password meter
  signup.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#354 fix title name in blog.html and review.html
  blog.html
  review.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#378 Added a Custom Cursor effect
  Blog_page.html
  Faq.html
  about-us.html
  blog.html
  contributors.html
  edition.html
  index.html
  login.html
  review.html
  signup.html
  welcome.html
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#383 Fixed the CONTACT US overflowing contents also changed the UI of canvas
  index.html
  src/Styles/Style.css
  src/Styles/contact_us_style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#294 i had tried to change the UI
  README.md
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#420 Confirmation Upon register
  signup.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#271 Added functionality to contact us form
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#261 Modified the navigation tab to highlight only the current tab.
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#440 The creation of new community page #412
  README.md
  about-us.html
  community.html
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#443 Bug Fix: Contributors section
  .github/workflows/add-contributors.yml
  .github/workflows/update_contributors.yml
  README.md
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#445 Added Contributor's Page
  contributors.html
  index.html
  src/Scripts/contributor.js
  src/Styles/Style.css
  src/Styles/contributor.css
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#446 Text size changed
  .vscode/settings.json
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#447 Fixed #416 - aligned submit button to center
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#465 Added Back to home button in Sign up page #460
  signup.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#477 Favicon added
  index.html
  resources/favicon.ico
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#481 signup and login page fixes
  login.html
  signup.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#496 contact us section improved #155
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#534 added clear canvas button functionality (working)
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#498 [FEAT]: Added more shapes
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#519 fix: 🐛 Fixed the contributors list table disorientation
  .github/workflows/add-contributors.yml
  README.md
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#509 Blank space Problem Solved
  login.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#520 Added eye icon for password field to toggle
  login.html
  signup.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#564 Updated Footer Icons, Reponsiveness on the Icons & Modified Program banners in README file
  Blog_page.html
  README.md
  about-us.html
  index.html
  privacy.html
  review.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#569 Update welcome.html
  about.html
  welcome.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#549 FAQ page header and Footer(issue #368)
  Faq.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#547 fixed color of topmost heading on homepage after toggle
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#550 faq enhanced and navbar navigations on different pages
  Blog_page.html
  Faq.html
  testimonial.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#607 Updated row.text.center.p-5 background color
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#608 fix: images, nav bar, removed duplicate items
  index.html
  resources/painting_image.jpg
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#611 Blog page placeholder text update
  Blog_page.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#612 Updated background color of footer
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#613 Changed the UI of the your message section
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#614 Added scroll bar
  Blog_page.html
  Faq.html
  about-us.html
  about.html
  blog.html
  community.html
  contributors.html
  edition.html
  index.html
  login.html
  privacy.html
  review.html
  signup.html
  src/Styles/Style.css
  src/Styles/scroll.css
  testimonial.html
  welcome.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#522 Button Styles added
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#618 Multi-Language Support Using Language Translator
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#622 improved blog page,scroll reveal
  Blog_page.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#623 docs: Enhanced And Added New Sections In Contributing.md
  Contributing.md
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#625 Made the necessary UI enhancements along with alignment correction in some part
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#649 Contact Us page proper alignment and message box alignment
  index.html
  src/Styles/contact_us_style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#653 🛠️FIX : Contact Us page - Name field validation
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#660 Added screenshots | Fixes #659
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#661 signup login enhance
  login.html
  signup.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#666 docs: removed depreciated hacktober fest logo and added a new one (fixed #665)
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#677 Implemented Save as Image funtionality of the canvas work
  index.html
  src/Scripts/Save.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#680 fixed proper orientation
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#676 change in css , changed font size for better visibility in style.css
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#718 FIX:ORIENTATION OF ABOUT US
  about-us.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#719 Contact us visibility problem solved
  src/Styles/contact_us_style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#692 Color palette improved.
  Blog_page.html
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#729 docs: Updated README.md
  README.md
  gssocextd.jpg
  hacktoberfest.png
Labels: gssoc-ext, level3, hacktoberfest-accepted

#763 Fixed the signup page input fields text to be more visible
  login.html
  signup.html
Labels: gssoc-ext, level3, hacktoberfest-accepted

#764 feat: Automated project structure updation using github workflows, python scripts and action bot
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  README.md
  repo_structure.txt
Labels: gssoc-ext, level2, hacktoberfest-accepted

#768 Fixed duplicate element from Footer in homepage
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#770 Fixed homepage
  index.html
Labels: gssoc-ext, level3, hacktoberfest-accepted

#774 fixed review for some devices
  repreviewfix.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#756 changed position of nav bar
  README.md
  index.html
  repo_structure.txt
  src/Styles/Style.css
Labels: gssoc-ext, level3, hacktoberfest-accepted

#776 Fixed About us Footer
  about-us.html
Labels: gssoc-ext, level3, hacktoberfest-accepted

#773 Fixed Your Message in homepage
  index.html
Labels: merge-conflict 😓

#789 Removed duplicate cards in blogs page and also made the heading visible
  Blog_page.html
  src/Styles/Style_Blog_page.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#795 Add a Translation Tool done ! #778
  Faq.html
  about.html
  index.html
Labels: gssoc-ext, level3, hacktoberfest-accepted

#829 Add a new contributors page done ! #777
  index.html
  src/Contributor.css
  src/Contributor.html
  src/Contributor.js
Labels: gssoc-ext, level3, hacktoberfest-accepted

#865 ✨Add Visitor Counter feature done ! #852
  index.html
  visi.css
  visi.js
Labels: gssoc-ext, level3, hacktoberfest-accepted

#797 About us Re-designed
  about-us.html
Labels: gssoc-ext, level3, hacktoberfest-accepted

#853 Added scrollbar for mobile version of FAQ page
  Faq.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#839 Style: Button UI
  src/Styles/Style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#790 Home page elements fixed
  index.html
  src/Styles/Style.css
  src/Styles/contact_us_style.css
Labels: gssoc-ext, level3, hacktoberfest-accepted

#860 (Fix)Navigation Bar Visual Issues - Spacing and Alignment has been Fixed.
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#807 Add Dark theme at home page
  blog.html
  index.html
Labels: gssoc-ext, level3, hacktoberfest-accepted

#882 Contact us form enhanced
  src/Styles/Style.css
  src/Styles/contact_us_style.css
Labels: merge-conflict 😓

#856 Fixed contributors alignment on mobile version
  src/Styles/contributor.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#903 FIX : Duplicate navbar on Testimonial page
  testimonial.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#912 Fixed Homepage
  .vscode/settings.json
  README.md
  index.html
  repo_structure.txt
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#899 FIX: Commented line is visible on Sign up page
  signup.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#871 Realigning and redesigning of buttons
  index.html
  src/Styles/Style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#835 fix: Made the tools buttons working
  index.html
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#831 updated readme with troubleshooting section
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#814 making contact us text visible
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#808 Dark mode toggle improved
  index.html
  logo4.png
  src/Styles/Style.css
  src/Styles/contact_us_style.css
Labels: gssoc-ext, level3, hacktoberfest-accepted

#805 done
  signup.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#799 Updating the about page
  about.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#794 Added different font styles,font weights and font family
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#741 Review can show
  review.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#933 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#934 Fixed whole home page
  README.md
  index.html
  repo_structure.txt
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#939 LOGIN AND CONTACT US SECTION
  index.html
  login.html
  src/Styles/Style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#850 Bug fixed in index.html
  index.html
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#862 Make responsive contact section
  index.html
  src/Styles/contact_us_style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#954 Shamvrueth
  review.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#958 Fixed and Enabled Progress Bar and Chatbot .
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest
