Repository vishanurag/Canvas-Editor, pull requests merged in 2024-11, with the labels that each got.

#1135 Changed the appearance of h1 under Navbar
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1142 Dash eye Icon Script added
  auth.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1137 refactor: Merge duplicate issue_template folders in .github for better clarity
  .github/Issue_templates/bug.yml
  .github/Issue_templates/feature.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#1141 Create basictemp.html
  basictemp.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#1144 feat: Redesign the tutorial page according to the theme.Issue(#1107)
  index.html
  tutorial.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1151 Fixed Feedback Forum
  Feedback.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#1153 auth.html code added
  auth.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1154 feat:Add User Question Submission Form to FAQ Page (#1113)
  Faq.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1155 Added hover effects in FAQ
  Faq.html
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1156 Added and enhanced contact page design
  src/Styles/contact.css
  src/Styles/contact.html
  src/Styles/contact_us_style.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#1157 README.md Update for contact form
  README.md
Labels: gssoc-ext, hacktoberfest-accepted

#1159 feat: Redesigning of the testimonial page(#771)
  testimonial.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1161 Made the About us page functional and maintained the same navbar all across the pages.
  Blog_page.html
  Faq.html
  about-us.html
  auth.css
  auth.html
  contributors.html
  index.html
  privacy.html
  review.html
  testimonial.html
  tutorial.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1182 feat: Enhanced scroll back button to all the pages with a progress ring.
  Blog_page.html
  Faq.html
  about-us.html
  about.html
  blog.html
  contributors.html
  privacy.html
  review.html
  testimonial.html
  tutorial.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1181 Add a User Profiles page done ! #1143
  index.html
  profile.html
  testp.css
  testp.js
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1199 about page inhanced
  about-us.html
  story.jpg
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1210 feat: Redesign the faq page according to the theme. (Issue#1168)
  Faq.html
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#1196 Added progress bar
  Blog_page.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#1216 Fixed whole tutorial page
  README.md
  repo_structure.txt
  testimonial.html
  tutorial.html
Labels: gssoc-ext, level2

#1208 Added dragging visibility for all shapes
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1211 Enhancing the CSS styling of the contact us form✨
  contact.html
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1212 Adding footer to the contributors section.
  contributors.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1218 Add Project Statistics in Contributors page done ! #1203
  contributors.html
  style.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1222 💥FIX : FAQ Auto close issue
  Faq.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1223 Revamped Canvas Editor Interface with Vibrant Icons
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1237 🛠️FIX : Mouse animation error on feedback page
  Feedback.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#1238 feat:Added scrollup button in FAQpage
  Faq.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1239 Update index.html
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1241 ADD Backend Issue Report Template
  .github/Issue_templates/backend_issue.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1243 🛠️FIX : Mouse animation and many more
  about-us.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1242 ADD Front end Issue Report Template
  .github/ISSUE_TEMPLATE/frontend_issue.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1245 feat:Added footer section to different pages
  Faq.html
  about-us.html
  privacy.html
  testimonial.html
  tutorial.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1246 🛠️FIX : Broken image on About Us page
  about-us.html
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1247 Add Edit Profile Feature in Profile Page done ! #1214 🟢🟢🟢
  index.html
  profile.html
  profileedit.html
  testp.js
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#1249 💥FIX : Missing Mouse animation on Tutorial page
  tutorial.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#1252 Modified community.html page
  community.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1217 feat: Redesign the privacy page according to the theme. Isssue#1189
  Mini-canvas-painting-bird-of-paradise-1.jpg
  canvas.jpg
  m_gen_canvas-square-p1_72f6de51-aaf7-4177-b19a-c8aae91404be.avif
  privacy.html
  testimonial.html
  tutorial.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1251 💥FIX : Broken images on Blog page and Back to Top button
  Blog_page.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#1254 💥FIX : Navbar position and remove unwanted code blocks
  contributors.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#1266 Add GitHub Workflow for Auto-Closing Similar Issue Requests
  .github/workflows/detect-duplicate.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1270 Remove duplicate login/sign up page button done 🐞🐞🐞 ! #1269
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1263 Enables the pwa feature on the website
  README.md
  icon-192x192.png
  icon-512x512.png
  index.html
  manifest.json
  repo_structure.txt
  scripts.js
  sw.js
Labels: gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#1276 Add same header in all page done ! #1275 ❇️❇️❇️
  Blog_page.html
  Faq.html
  about-us.html
  privacy.html
  review.html
  testimonial.html
  tutorial.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1279 💥FIX : Static Happy Clients count on Testimonial page
  testimonial.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1286 [BUG] fix the cursor animation, check description #1194
  Blog_page.html
  Faq.html
  about-us.html
  about.html
  blog.html
  community.html
  contact.html
  edition.html
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#1256 💥FIX : Name validation added
  Faq.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1258 💥FIX : Missing mouse animation on Review page
  review.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1260 💥FIX : broken Images on Testimonial page
  testimonial.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1262 💥FIX : Missing Mouse animation added
  testimonial.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1265 💥FIX : Name validation added on Feedback form page
  Feedback.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1281 💥FIX : Missing mouse animation on Profile page
  profile.html
  testp.css
  testp.js
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1283 💥FIX : Missing mouse animation on Auth page
  auth.css
  auth.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1285 💥FIX : Missing mouse animation on Edit Profile page
  profileedit.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1274 Fixed Header misalignment in contributors page done 🐞🐞🐞! #1271
  contributors.html
Labels: gssoc-ext, level1, hacktoberfest-accepted, hacktoberfest

#1289 refactored privacy.html and removed overflow, added navbar toggler
  privacy.html
Labels: bug-fix 🛠️
