Repository vishanurag/Canvas-Editor, pull requests merged in 2025-08, with the labels that each got.

#1305 Enhance Tutorial Cards with 3D Hover Transition Effect for Better UI Feedback #1303
  tutorial.html
Labels: level1, gssoc25

#1306 UI successfully improved
  Blog_page.html
  Faq.html
  Feedback.html
  about-us.html
  auth.css
  auth.html
  contact.html
  contributors.html
  index.html
  privacy.html
  profile.html
  review.html
  testimonial.html
  testp.css
  testp.js
  tutorial.html
Labels: level3, gssoc25

#1321 📄 Added MIT License section to README
  README.md
Labels: level1, gssoc25

#1319 Added Clear Canvas Button (Fixes #1297)
  index.html
Labels: level1, gssoc25

#1345 Resolve overlap between visitor counter and chat icon
  Faq.html
  index.html
Labels: good first issue, level1, gssoc25

#1347 SOlved issue #1344 footer Ui enhance and typing animation added in all Nav links
  Blog_page.html
  Faq.html
  about-us.html
  blog.html
  index.html
  privacy.html
  review.html
  src/Scripts/typing.js
  src/Styles/typing.css
  testimonial.html
  tutorial.html
Labels: level2, gssoc25

#1349 feat: improved Home Page frontend UI and styling for better appearance
  index.html
Labels: level2, gssoc25

#1356 style: update Visitor button color to match theme
  index.html
Labels: level1, gssoc25
